### ISSUE TITLE
Causes node-red to crash

### ISSUE THREAD

**Issue by kylegordon** [AntoineLT/ttb-node-owntracks#1]
Hey,

After a plain npm install -g ttb-node-owntracks all appears to be well, until a node is deployed. I used a basic hostname of my MQTT broker (Mosquitto 1.4.7-1 on Debian Jessie), and my Owntracks topic. Nothing else was specified, and I didn't hook the output of the node to anything :)

```
node-red-0 2 Feb 17:05:22 - [info] [mqtt-broker:66a92c76.9956d4] Connected to broker: mqtt://homeauto.vpn.glasgownet.com:1883
node-red-0 2 Feb 17:05:22 - [mqtt] [bd88feba.4277] connected to broker tcp://mqtt.vpn.glasgownet.com:1883
node-red-0 2 Feb 17:05:22 - [red] Uncaught Exception:
node-red-0 2 Feb 17:05:22 - TypeError: self.client.setPacketEncoding is not a function
node-red-0     at MQTTClient.subscribe (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:197:19)
node-red-0     at MQTTClient.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqttConnectionPool.js:129:40)
node-red-0     at emitNone (events.js:72:20)
node-red-0     at MQTTClient.emit (events.js:166:7)
node-red-0     at Connection.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:115:28)
node-red-0     at emitOne (events.js:77:13)
node-red-0     at Connection.emit (events.js:169:7)
node-red-0     at Connection.emitPacket (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/mqtt-connection/connection.js:13:8)
node-red-0     at emitOne (events.js:77:13)
node-red-0     at Connection.emit (events.js:169:7)
node-red-0 TypeError: self.client.setPacketEncoding is not a function
node-red-0     at MQTTClient.subscribe (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:197:19)
node-red-0     at MQTTClient.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqttConnectionPool.js:129:40)
node-red-0     at emitNone (events.js:72:20)
node-red-0     at MQTTClient.emit (events.js:166:7)
node-red-0     at Connection.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:115:28)
node-red-0     at emitOne (events.js:77:13)
node-red-0     at Connection.emit (events.js:169:7)
node-red-0     at Connection.emitPacket (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/mqtt-connection/connection.js:13:8)
node-red-0     at emitOne (events.js:77:13)
node-red-0     at Connection.emit (events.js:169:7)
node-red-0 Welcome to Node-RED
node-red-0 ===================
...

node-red then continues to crash and be restarted by pm2

node-red-0 2 Feb 17:05:23 - [info] Node-RED version: v0.12.2
node-red-0 2 Feb 17:05:23 - [info] Node.js  version: v4.2.6

Happy to do testing and help out
```

**Comment by altDAW** [comment]
Hi,

Your error seems to come from the declaration of the MQTT client.
Indeed this is made to work on The ThingBox and in the filesystem the MQTT
client is in the folder :
'/root/thethingbox/node_modules/node-red/node_modules/
nodes/core/io/lib/mqttConnectionPool'.
Your OS is not configured to work with.
If you want this not to work you have to modify the line 10 in owntracks.js
that declare the location of the MQTT Connection Pool.
Without this the node wasn't tested.

I hope tha will be cleared and this explanation will solve your problem!

Regards,

Antoine LA TORRE

2016-02-02 18:12 GMT+01:00 Kyle Gordon notifications@github.com:

> Hey,
> 
> After a plain npm install -g ttb-node-owntracks all appears to be well,
> until a node is deployed. I used a basic hostname of my MQTT broker
> (Mosquitto 1.4.7-1 on Debian Jessie), and my Owntracks topic. Nothing else
> was specified, and I didn't hook the output of the node to anything :)
> 
> node-red-0 2 Feb 17:05:22 - [info] [mqtt-broker:66a92c76.9956d4] Connected to broker: mqtt://homeauto.vpn.glasgownet.com:1883
> node-red-0 2 Feb 17:05:22 - [mqtt] [bd88feba.4277] connected to broker tcp://mqtt.vpn.glasgownet.com:1883
> node-red-0 2 Feb 17:05:22 - [red] Uncaught Exception:
> node-red-0 2 Feb 17:05:22 - TypeError: self.client.setPacketEncoding is not a function
> node-red-0     at MQTTClient.subscribe (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:197:19)
> node-red-0     at MQTTClient.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqttConnectionPool.js:129:40)
> node-red-0     at emitNone (events.js:72:20)
> node-red-0     at MQTTClient.emit (events.js:166:7)
> node-red-0     at Connection.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:115:28)
> node-red-0     at emitOne (events.js:77:13)
> node-red-0     at Connection.emit (events.js:169:7)
> node-red-0     at Connection.emitPacket (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/mqtt-connection/connection.js:13:8)
> node-red-0     at emitOne (events.js:77:13)
> node-red-0     at Connection.emit (events.js:169:7)
> node-red-0 TypeError: self.client.setPacketEncoding is not a function
> node-red-0     at MQTTClient.subscribe (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:197:19)
> node-red-0     at MQTTClient.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqttConnectionPool.js:129:40)
> node-red-0     at emitNone (events.js:72:20)
> node-red-0     at MQTTClient.emit (events.js:166:7)
> node-red-0     at Connection.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/lib/mqtt.js:115:28)
> node-red-0     at emitOne (events.js:77:13)
> node-red-0     at Connection.emit (events.js:169:7)
> node-red-0     at Connection.emitPacket (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/mqtt-connection/connection.js:13:8)
> node-red-0     at emitOne (events.js:77:13)
> node-red-0     at Connection.emit (events.js:169:7)
> node-red-0 Welcome to Node-RED
> node-red-0 ===================
> ...
> 
> node-red-0 2 Feb 17:05:23 - [info] Node-RED version: v0.12.2
> node-red-0 2 Feb 17:05:23 - [info] Node.js  version: v4.2.6
> 
> Happy to do testing and help out
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AntoineLT/ttb-node-owntracks/issues/1.

## 

_Antoine LA TORRE_
Tel : +33 (0)6 01 01 87 08
